### ISSUE TITLE
Stuck event loop after network 'failure' in long running proces with libevent

### ISSUE THREAD

**Issue by kingkorf** [nats-io/nats.c#348] opened 2020-07-17 13:51 UTC
Hi, 

I'm working on a project that wants to both publish and subscribe to a NATS cluster. I'm using libevent as an event loop and I'm binding some events. In two of these events I'm publishing to a certain channel with natsConnection_PublishString, this all goes well until I disconnect the network. When I reinsert the cable after a few minutes the whole event loop seems to be stuck and nothing happens afterwards, it looks like the whole loop is stuck somehow. Of course I want the reconnect logic to kick in here and start publishing again.

I'm reading the following in the documentation:

"Where it becomes tricky is when publishing data. Indeed, publishing is merely putting data in a buffer, and it is the event library that will notify a callback that write to the socket should be performed. For that, the event loop needs to be 'running'."

"So if you publish from the thread where the event loop is running, you need to 'run' the loop after each (or a number) of publish calls in order for data to actually be sent out. Alternatively, you can publish from a different thread than the thread running the event loop."

What does it mean to 'run' the loop after each publish call? And/or how can I use the libevent-pub example code (that works with separate threads for publishing) to work in a long running process that wants to keep connection?

**Comment by kozlovic** [comment] 2020-07-17 15:37
> What does it mean to 'run' the loop after each publish call?

Why are you using libevent in the first place? Are you required to use it? If so, I would recommend that you learn more about it. In a nutshell, the event loop processes events/timers and fires registered callbacks when a specific file descriptor has data to be written/read. When your code calls natsConnection_Publish(), the data is simply copied to a buffer. Only when libevent's event loop runs will it invoke the NATS callback that will perform the write to the socket.

If you unplug/plug back the cable, the TCP stack does not report the connection as broken. This is why most applications use PINGs to detect this situation faster. In the NATS C client, the default PING is every 2 minutes and will wait for 2 failures to get the PONG back before reporting the connection as staled.

Did you wait long enough? Alternatively, lower the ping interval (`natsOptions_SetPingInterval()`) and see if that makes a difference.

**Comment by kingkorf** [comment] 2020-07-21 15:04
Hi Ivan, thanks for the reply. 

I tweaked the ping/pong mechanism and the write deadline a bit but eventually found that the event_base_dispatch function from libevent calls event_base_loop which can be given the parameter EVLOOP_NONBLOCK, this seems to do the trick. 

So instead of starting the loop with event_base_dispatch(evLoop) you can run it with event_base_loop(evLoop, EVLOOP_NONBLOCK), when a disconnect occurs the loop now keeps going and as soon as there is a connection NATS will reconnect. The documentation on this is quite cryptic: 

"You can change the behavior of event_base_loop() by setting one or more flags in its flags argument. If EVLOOP_ONCE is set, then the loop will wait until some events become active, then run active events until there are no more to run, then return. If EVLOOP_NONBLOCK is set, then the loop will not wait for events to trigger: it will only check whether any events are ready to trigger immediately, and run their callbacks if so." (http://www.wangafu.net/~nickm/libevent-book/Ref3_eventloop.html)

Maybe this behavior can be explained in the documentation of this library.

**Comment by kozlovic** [comment] 2020-07-21 15:54
You can always call `event_base_loop()` with `EVLOOP_NONBLOCK`, but the problem is that you would have to decide when to call this function. For instance, if you do it after each publish call, then it would work but performance will suffer because each publish may result in a TCP write, which will reduce throughput.
Also be aware that the function will not block if there is no event, but if there is one, will invoke the callback, but does not mean that all the buffers are flushed, so you should always ensure that the event loop is running, one way or another.

Regardless on how you run the event loop, I don't think that it explains the inability to reconnect. The examples that are provided in this repo and that use `event_base_dispatch` can reconnect just fine. At least the subscriber can. The publisher is likely to fail because the publish occurs in a different thread and once disconnected (at least when the TCP connection is reported as broken), the Publish() call at one point will fail because the memory pending buffer - used during disconnect state - will fill up quickly and the connection will be closed (see `pubThread` function in `examples/libevent-pub.c`), which will release `event_base_dispatch()` which will stop the bench program.

> Maybe this behavior can be explained in the documentation of this library.

I honestly think that this is out of scope. I can't be documenting the use and full details of libuv or libevent in this repo's README. I do point users to the respective event loop's github repo where they can find the appropriate documentation. I already alert users about the need to ensure that the event loop is running for messages to be sent out or messages callback to be invoked.
And again, my assumption is that if a user choose to use an external event loop, it is because there is a requirement to do so and that the user is familiar with the chosen event loop library. If there is no need/requirement, I would recommend starting with NATS only.

**Closed by kozlovic** 2020-07-21 15:54 UTC
