### ISSUE TITLE
Question: sendAsap option and its behaviour

### ISSUE THREAD

**Issue by paoloteti** [nats-io/nats.c#393] opened 2020-12-29 10:51 UTC
I have a question about `sendAsap` option. 
The meaning is clear, but it is not clear why such option is not present in `nats.go` (and may be in other clients) where, if I'm not wrong, the flusher goroutine is always started and kicked when needed. 
I'm missing some details of `nats.go` (may be, since I'm not really familiar with it) or this create an asimmetry between the two clients?

Thanks.

**Comment by kozlovic** [comment] 2020-12-29 17:17
When I started writing the C client, I took model of the nats.go client (most of the Synadia produced clients use the Go client as the model).
The Go language as the concept of "channel" which is used to notify the flusher go routine to send messages. When the "publish" call notifies the flusher, its go routine is likely not to execute unless there is an I/O wait.. that is, say that you publish 1,000,000 messages in the bench tool and you were to count and then print how many times the flusher would actually be executed, it would be very low. The "publish" uses a buffered writer that will write to the socket when reaching capacity (we use a 32K buffer). So the routine doing the "publish" calls in a loop basically almost always keep control and do the send in place when buffer is filled.

In the C client, I did not have Go channels, so I used a condition variable that would be notified when something was added to the buffer. The problem is by doing that, the flusher would get notified and always take control and basically send 1 message at a time, which was really bad, throughput wise. So I resorted to something really ugly, is to have the flusher wait for 1ms before really attempting to flush. In the same case than described above, then the publisher thread would behave almost like the Go client, having the chance to fill its outbound buffer and do the write in place. I always wanted to get back to that, but never found the time and "it kind of works", so there is less urgency. However, for users that favor the latency over the throughput, I added this option so that the message is sent as soon as possible (the buffer content is written in place), so we don't suffer from the 1ms delay that would be introduced by the flusher.
By the way, since Request() by nature send and wait for reply, those call always write in place (don't use the flusher). But for users that want to use PublishRequest() (because they create their own subscription to get the reply or replies), then they can use this option to make sure that the content is also flushed right away.

We don't need that in Go, because Go is good at both conditions: if there are lots of publish calls, then the flusher is not taking control and let the buffer grow, but if there is a single publish, then the flusher quickly flushes.

I hope this helps.

**Comment by paoloteti** [comment] 2020-12-30 14:05
Thanks, clear explaination. To be onest I don't use it in C. I noticed it by chance looking of a `SetPedantic` equivalent in `nats.go`.
There are few go channel emulation libs in C both based on pthread_cond_wait/cond_signal, of course, one per channel, so nothing wrong the condition variable itself.
I let the "issue" open if someone else could be interested or may be can be used as reference in the future. 
**Close it, otherwise.**

Thanks again.

**Comment by kozlovic** [comment] 2020-12-30 17:32
@paoloteti Thanks. I am closing this, but will reference if someone has the same question.

**Closed by kozlovic** 2020-12-30 17:32 UTC
Labels: question
