### ISSUE TITLE
How to make onMsg callback as non static c++ class member?

### ISSUE THREAD

**Issue by kv-gits** [nats-io/nats.c#337] opened 2020-06-16 18:58 UTC
I try to set onMsg callback this way
```
void NatsTransport::Start() {
    s = natsConnection_ConnectTo(&conn, NATS_DEFAULT_URL);
    if (s == NATS_OK) {
        // Creates an asynchronous subscription on subject "foo".
        // When a message is sent on subject "foo", the callback
        // onMsg() will be invoked by the client library.
        // You can pass a closure as the last argument.
        s = natsConnection_Subscribe(&sub, conn, "foo", &NatsTransport::onMsg, NULL);
    }
}
...
// class member declaration
 void onMsg(natsConnection *nc, natsSubscription *sub, natsMsg *msg, void *closure); // callback
```

Get error types mismatch. How to pass class member as callback, could you provide miniexample please?

**Comment by kozlovic** [comment] 2020-06-16 21:31
This is a duplicate of #233 and there was a solution proposed [here](https://github.com/nats-io/nats.c/issues/233#issuecomment-507497184):
```
s = natsConnection_Subscribe(&sub, nc, "foo", onMsg, this);

onMsg function do:
SomeClass obj = (SomeClass)closure;
obj->onMsg(...);
```
Meaning that you would pass a static C onMsg callback which would use the closure (user pointer) to cast to your C++ class and then call its own message handler callback.

**Closed by kozlovic** 2020-06-16 21:31 UTC
