### ISSUE TITLE
Repeated embedded message of floats are received with value 0

### ISSUE THREAD

**Issue by PrajwalNReddy** [nats-io/nats.c#266] opened 2019-09-24 05:56 UTC
Hi all,

We tried using protobuf with cnats. We are trying to send embedded message which contains float repeatedly in another message. Refer the proto file attached.
[cube.proto.log](https://github.com/nats-io/nats.c/files/3645417/cube.proto.log)

We are receiving floats as 0 always.

Below is the code snippet for sending part.
cubeTest::Cube cube;
cubeTest::Square* square = cube.add_square();
square->set_length(2.5);
std::string msgToSend = cube.SerializeAsString();
natsStatus status = natsConnection_PublishString(conn,"foo", msgToSend.c_str());

Below is the code snippet for the recieving part.
natsStatus status = natsConnection_Subscribe(&sub, conn, "foo", onMsgCube, NULL);

static void
onMsgCube(natsConnection *nc, natsSubscription *sub, natsMsg *msg, void *closure)
{
  std::cout<<"Received msg: "<<natsMsg_GetSubject(msg)<<std::endl;
  std::cout<<natsMsg_GetData(msg)<<std::endl;
  std::cout<<natsMsg_GetDataLength(msg)<<std::endl;

  cubeTest::Cube cube;
  cube.ParseFromString(natsMsg_GetData(msg));
  const cubeTest::Square& square = cube.square(0);
  std::cout<<"square : "<<square.length()<<std::endl;

 natsMsg_Destroy(msg);
}

We also tried reciever on python client and the message is correctly with proper float value.
We have also tried sending embedded message which contains int repeatedly in another message and it is also parsed properly.

We are unable to root cause down the issue to which component(cnats or protobuf).
Please guide us in resolving this issue.

Thank You

**Comment by kozlovic** [comment] 2019-09-24 15:25
Several things you should check:
- `std::string msgToSend = cube.SerializeAsString();`: make sure that this is returning a valid (non empty) ASCII string. Otherwise, use a byte serialization and simply call `natsConnection_Publish()` with the byte array and length.
- `cube.ParseFromString(natsMsg_GetData(msg));`: for that to work it implies that the data in the message is a string with `\0` terminating character. See also the point above for the encoding.
- Have you tried sending from other type of client and see if you can receive ok? And vice versa (sending from your C app and check if you can receive ok in python client.

The NATS C client uses protobuf for the Streaming layer, so using protobuf with the NATS C library should work. NATS sends/receives message payload as an "opaque" byte array, that is, the protocol to send a message is "PUB <subject> <length of payload> <payload>\r\n", so it does not matter what is in the payload (could be all 0s) the server and library does not interpret it.

**Comment by PrajwalNReddy** [comment] 2019-09-25 09:20
- At the sender, we did parse the string using ParseFromString() and it did parse with correct values.Also the same API(natsConnection_Publish) works with embedded message which contains int repeatedly in another message. The problem is with only float.
- We tried the sending the same message using python client and we were able to receive correctly on the C app.
- We have also tried sending the message using natsConnection_Publish,natsConnection_PublishString and natsConnection_PublishMsg. None of them helped us.

Thank You

**Comment by kozlovic** [comment] 2019-09-25 15:10
As I said, NATS does not do anything with the payload, meaning that if you call `natsConnection_Publish()` you pass a byte array and its length and that will be copied to the byte buffer being sent. The server does not look at the payload and again the subscriber receives a protocol of the form: `MSG <subject> <subscription id> <length> <payload>\r\n` and a message is constructed from there with "Data" being a copy of the `<payload>` in that protocol.
I strongly suspect that the serialization is either wrong or you are not passing the correct byte array/length. Do you have a function to serialize as a byte array instead of a "string"?

**Comment by PrajwalNReddy** [comment] 2019-09-26 06:24
Thanks for the information.

I tried parsing the protobuf as a byte array.
Below is the code snippet
size_t size = cube.ByteSizeLong(); 
void *buffer = malloc(size);
cube.SerializeToArray(buffer, size);

and at the reciever,parsed the incoming payload as
cube.ParseFromArray(natsMsg_GetData(msg),natsMsg_GetDataLength(msg));

I was able to receive the float values correctly.

**Comment by kozlovic** [comment] 2019-09-26 15:04
Yes, so as I suspected, the issue is with cube.SerializeAsString(), or at least its content and the result of calling strlen() on that string.

Here is some details about how sending/receiving messages work at the library level:

When you use `natsConnection_PublishString()`, the API expects a `const char *` that is interpreted as a byte array which length is determined by calling `strlen()` on it, which returns the length (excluding the NULL terminated character). So if string is `'f', 'o', 'o', '\0'`, it returns 3 and will have only `f`, `o`, `o` sent on the wire (but remember, the `PUB` protocol has the size of the payload before the payload, so that's fine).
 
However, the NATS C client when receiving a message will add a `\0` at the end of the payload so that if you call `natsMsg_Data()` and you know that this is a string, you don't have to do anything special (like allocating memory of `natsMsg_GetDataLength()` + 1, copy `natsMsg_Data()` and add the `\0` so that your application can use that as a string).

Nothing above explains why it would not work with `cube.SerializeAsString()` as long as this produces a valid NULL terminated string. You can see in our examples (examples/getstarted/pubstr.c) or in our tests (test/test.c) that we use `natsConnection_PublishString()` and this works fine.

**Comment by kozlovic** [comment] 2019-09-30 16:50
@PrajwalNReddy I do not believe that there is an issue with the NATS C client library, but if there is, I would like to fix it before the next release that I am planning to have soon. Let me know if you still have issues or if it is ok to close this.

**Comment by kozlovic** [comment] 2019-10-02 16:15
@PrajwalNReddy Any news? I am closing this for now and will issue a release soon. Don't hesitate to send some info and I will re-open if needed.

**Closed by kozlovic** 2019-10-02 16:15 UTC
